#!/bin/bash -p
#
# prime before running with 'sudo date'
#
# See www.noobslab.com/2015/10/top-things-and-tweaks-to-do-after.html
#
function do_install () {
  date
  printf "\nInstalling $*\n\n"
  sudo apt-get install -y $*
}

do_install openssh_server

do_install perl

do_install aptitude

printf "\nEnabling partners in /etc/apt/sources.list\n\n"
sudo perl -wpi.back /etc/apt/sources.list '/^#deb.*partner/ and s/^#//;'

do_install compizconfig-settings-manager

printf "\nEnabling recursive search for Nautilus\n\n"
gsettings set org.gnome.nautilus.preferences enable-interactive-search false

printf "\nEnabling real name on panel\n\n"
gsettings set com.canonical.indicator.session show-real-name-on-panel true

# firewall:
do_install gufw

# codecs:
do_install ffmpeg gstreamer0.10-plugins-ugly gxine libdvdread4 \
  icedax tagtool easytag id3tool lame libxine2-ffmpeg \
  nautilus-script-audio-convert libmad0 mpg321 libavcodec-extra \
  gstreamer1.0-libav 

# enable dvd playback
printf "\nEnable DVD playback:\n\n"
sudo /usr/share/doc/libdvdread4/install-css.sh

# compression tools:
do_install p7zip-rar p7zip-full unace unrar zip unzip sharutils rar \
  uudeview mpack arj cabextract file-roller

do_install unp # <-- useful wrapper around tar, etc.

do_install git-all git-extras

printf "\nGetting random/scripts and setting it up links in ~/bin\n\n"
mkdir -p ~/bin
cd bin
git clone http://172.40.40.24/random/scripts.git
ln -s scripts/* .

printf "\nStart a new terminal, and ensure that ~/bin is in your path\n\n"

export PATH=$PATH:/usr/local/bin:$HOME/bin:.

do_install imagemagick
do_install vim
do_install build-essential
do_install flex
do_install qt4-qmake

printf "\nBuilding bison\n\n"
cd
wget http://ftp.gnu.org/gnu/bison/bison-2.7.1.tar.gz
unp bison-2.7.1.tar.gz
cd bison-2.7.1.tar.gz
./configure
make
sudo make install
sudo chmod -R a+rX /usr/local

printf "\nBuilding xxdiff\n\n"
wget http://downloads.sourceforge.net/project/xxdiff/xxdiff/4.0/xxdiff-4.0.tar.bz2
unp xxdiff-4.0.tar.bz2
cd xxdiff-4.0/src
make -f Makefile.bootstrap
make
cd ../bin
sudo mv * /usr/local/bin
sudo chmod -R a+rX /usr/local

